matrix:
  include:
  - language: android
    sudo: required
    jdk: oraclejdk8
    android:
      components:
        - tools
        - platform-tools
        # The BuildTools version used by your project
        - build-tools-26.0.2
        # The SDK version used to compile your project
        - android-26
        - android-22
        - android-24
        # Additional components
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository
        - addon-google_apis-google-26
        # Specify at least one system image,
        # if you need to run emulator(s) during your tests
        - sys-img-armeabi-v7a-android-22
    # Emulator Management: Create, Start and Wait
    before_script:
      - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
      - emulator -avd test -no-skin -no-audio -no-window &
      - android-wait-for-emulator

  - language: node_js
    before_install : 
      - sudo apt-get install openjdk-8-jdk
      - sudo apt-get install openjdk-8-jre
    install :
      - npm install appium
      - npm install appium-doctor
    script:
      - appium-doctor
      # need to specify chrome driver
      - appium

  - language: python
    python:
      - "3.5"
    install:
      - pip install -r requirements.txt
    script:
      - python -V
      - pytest