language: android
sudo: required
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-26.0.2
    # The SDK version used to compile your project
    - android-26
    - android-22
    - android-24
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26
    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-24
# Emulator Management: Create, Start and Wait
before_install:
  - sudo apt-get update
  # install pyenv
  - sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev
  - git clone https://github.com/pyenv/pyenv.git ~/.pyenv
  - echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bash_profile
  - echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_profile
  - echo 'eval "$(pyenv init -)"' >> ~/.bash_profile
  # install virtualenv
  - git clone https://github.com/yyuu/pyenv-virtualenv.git ~/.pyenv/plugins/pyenv-virtualenv
  - echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bash_profile
  # reload .bash_profile
  - source ~/.bash_profile
  # install python
  - pyenv versions
  - pyenv install 3.6.1
  # make virtualenv
  - pyenv virtualenv 3.6.1 undang
  # activate virtualenv
  - pyenv activate undang
  # check python version
  - python -V
  # install packages
  - pip install --user -r requirements.txt
  # install node
  - curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
  - sudo apt-get install nodejs
  - sudo apt-get install build-essential
  - nodejs -v
  - node -v
  # install appium
  - npm install appium --chromedriver_version="2.33"
  - npm install appium-doctor
  # run appium-doctor
  - appium-doctor
  - appium &

before_script:
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

